apiVersion: v1
kind: Namespace
metadata:
  name: geekshopping
---
apiVersion: v1
kind: Service
metadata:
  namespace: geekshopping
  name: api-gateway-svc
spec:
  selector:
    app: api-gateway
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: geekshopping
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: api-gateway:minikube
        env:
          - name: AuthSettings:IdentityUrl
            value: http://identity-server-svc
        resources:
          limits:
            memory: 100Mi
            cpu: 100m
        ports:
        - containerPort: 80
