apiVersion: v1
kind: Namespace
metadata:
  name: geekshopping
---
apiVersion: v1
kind: Service
metadata:
  namespace: geekshopping
  name: identity-server-db-svc
spec:
  selector:
    app: identity-server-db
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: geekshopping
  name: identity-server-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-server-db
  template:
    metadata:
      labels:
        app: identity-server-db
    spec:
      containers:
      - name: identity-server-db
        image: mysql:latest
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: mypassword
          - name: MYSQL_DATABASE
            value: geek_shopping_identity_server
        resources:
          limits:
            memory: 100Mi
            cpu: 100m
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  namespace: geekshopping
  name: identity-server-svc
spec:
  selector:
    app: identity-server
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: geekshopping
  name: identity-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-server
  template:
    metadata:
      labels:
        app: identity-server
    spec:
      containers:
      - name: identity-server
        image: localhost:5000/geekshopping-identityserver:minikube
        env:
          - name: MySQLConnection__MySQLConnectionString
            value: "Server=identity-server-db-svc;Database=geek_shopping_identity_server;Uid=root;Pwd=mypassword"
        resources:
          limits:
            memory: 100Mi
            cpu: 100m
        ports:
        - containerPort: 80

