apiVersion: v1
kind: Namespace
metadata:
  name: geekshopping
---
apiVersion: v1
kind: Service
metadata:
  namespace: geekshopping
  name: order-db-svc
spec:
  selector:
    app: order-db
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: geekshopping
  name: order-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-db
  template:
    metadata:
      labels:
        app: order-db
    spec:
      containers:
      - name: order-db
        image: mysql:latest
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: mypassword
          - name: MYSQL_DATABASE
            value: geek_shopping_order_api
        resources:
          limits:
            memory: 100Mi
            cpu: 100m
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  namespace: geekshopping
  name: order-api-svc
spec:
  selector:
    app: order-api
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: geekshopping
  name: order-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
      - name: order-api
        image: localhost:5000/order-api:minikube
        env:
          - name: MySQLConnection__MySQLConnectionString
            value: "Server=order-db-svc;DataBase=geek_shopping_order_api;Uid=root;Pwd=mypassword"
          - name: AuthSettings__IdentityUrl
            value: "http://identity-server-svc"
          - name: RabbitMqSettings__HostName
            value: "rabbitmq-svc"
          - name: RabbitMqSettings__UserName
            value: "guest"
          - name: RabbitMqSettings__Password
            value: "guest"
        resources:
          limits:
            memory: 100Mi
            cpu: 100m
        ports:
        - containerPort: 80
