apiVersion: v1
kind: Namespace
metadata:
  name: geekshopping
---
apiVersion: v1
kind: Service
metadata:
  namespace: geekshopping
  name: web-site-svc
spec:
  selector:
    app: web-site
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: geekshopping
  name: web-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-site
  template:
    metadata:
      labels:
        app: web-site
    spec:
      containers:
      - name: web-site
        image: localhost:5000/web-site:minikube
        env:
          - name: ServiceUrls__IdentityServer
            value: "http://identity-server-svc"
          - name: ServiceUrls__ProductAPI
            value: "http://api-gateway-svc"
          - name: ServiceUrls__CartAPI
            value: "http://api-gateway-svc"
          - name: ServiceUrls__CouponAPI
            value: "http://api-gateway-svc"
        resources:
          limits:
            memory: 100Mi
            cpu: 100m
        ports:
        - containerPort: 80

